### ISSUE TITLE
测试代码是不能运行的

### ISSUE THREAD

**Issue by wuxiaolianggit** [Data2040-Spring-2020-Team/Quarantine-Boys#2]
您好，大神，我下载您的代码，发现测试代码不能运行，你可以提供一个完成的可以运行人脸属性预测的脚本吗 @yahowang

**Comment by yahowang** [comment]
你好，测试代码是用于展现Wider Dataset的脸部label的好坏，而不是用于预测人脸属性(性别与年龄), 请考虑结合Preprocess+Network.ipynb 来实现预测。
